In [35]:
import numpy as np
from numpy import linalg as LA

In [36]:
A = np.array([[1, 0], [0, 1]])
print(A)

[[1 0]
 [0 1]]


In [37]:
eigenvalues, eigenvectors = LA.eig(A)
print("eigenvalues\n", eigenvalues)
print("eigenvectors\n", eigenvectors)

eigenvalues
 [1. 1.]
eigenvectors
 [[1. 0.]
 [0. 1.]]


In [38]:
# P -> composed of eigenvectors
# D -> composed of eigenvalues
P = eigenvectors
D = np.diag(eigenvalues)
P_inv = np.linalg.inv(P)
print("P\n", P)
print("D\n", D)
print("P_inv\n", P_inv)

P
 [[1. 0.]
 [0. 1.]]
D
 [[1. 0.]
 [0. 1.]]
P_inv
 [[1. 0.]
 [0. 1.]]


In [39]:
P @ D @ P_inv

array([[1., 0.],
       [0., 1.]])

## From chapter 25

In [40]:
A = np.array([[-3, 5], [4, -2]])
print(A)

[[-3  5]
 [ 4 -2]]


In [41]:
eigenvalues, eigenvectors = LA.eig(A)
print("eigenvalues\n", eigenvalues)
print("eigenvectors\n", eigenvectors)

eigenvalues
 [-7.  2.]
eigenvectors
 [[-0.78086881 -0.70710678]
 [ 0.62469505 -0.70710678]]


In [42]:
# P -> composed of eigenvectors
# D -> composed of eigenvalues
P = eigenvectors
D = np.diag(eigenvalues)
P_inv = np.linalg.inv(P)
print("P\n", P)
print("D\n", D)
print("P_inv\n", P_inv)

P
 [[-0.78086881 -0.70710678]
 [ 0.62469505 -0.70710678]]
D
 [[-7.  0.]
 [ 0.  2.]]
P_inv
 [[-0.71145825  0.71145825]
 [-0.62853936 -0.7856742 ]]


In [43]:
P @ D @ P_inv

array([[-3.,  5.],
       [ 4., -2.]])