In [ ]:
# Reference: https://www.youtube.com/watch?v=pkVwUVEHmfI&ab_channel=AladdinPersson

In [2]:
import torch
import numpy as np

In [3]:
x = torch.rand((2, 3))
print(x)

tensor([[0.0361, 0.3732, 0.2942],
        [0.9205, 0.2160, 0.9936]])


### Permutation of tensors

In [4]:
print(torch.einsum('ij->ji', x))

tensor([[0.0361, 0.9205],
        [0.3732, 0.2160],
        [0.2942, 0.9936]])


In [6]:
print(torch.transpose(x, 0, 1))

tensor([[0.0361, 0.9205],
        [0.3732, 0.2160],
        [0.2942, 0.9936]])


### Summation of tensors

In [7]:
print(torch.einsum('ij->', x))

tensor(2.8336)


In [8]:
print(torch.sum(x))

tensor(2.8336)


### Column sum 

In [9]:
print(torch.einsum('ij->j', x))

tensor([0.9566, 0.5892, 1.2878])


In [11]:
print(torch.sum(x, dim=0))

tensor([0.9566, 0.5892, 1.2878])


### Row sum

In [12]:
print(torch.einsum('ij->i', x))

tensor([0.7035, 2.1301])


In [13]:
print(torch.sum(x, dim=1))

tensor([0.7035, 2.1301])


### Matrix-vector multiplication

In [14]:
v = torch.rand((1, 3))
print(v)

tensor([[0.3621, 0.7341, 0.5005]])


In [16]:
print(torch.einsum('ij,kj->ik', x, v))

tensor([[0.4343],
        [0.9892]])


In [15]:
print(torch.matmul(x, v.transpose(1, 0)))

tensor([[0.4343],
        [0.9892]])


### Matrix-matrix multiplication

In [19]:
print(torch.einsum('ij,kj->ik', x, x))

tensor([[0.2272, 0.4062],
        [0.4062, 1.8811]])


In [18]:
print(torch.matmul(x, x.transpose(0, 1)))

tensor([[0.2272, 0.4062],
        [0.4062, 1.8811]])


### Dot product first row with first row of matrix

In [20]:
torch.einsum('i,i->', x[0], x[0])

tensor(0.2272)

### Dot product with matrix

In [21]:
torch.einsum('ij,ij->', x, x)

tensor(2.1083)

### Hadamard Product (element-wise multiplication)

In [22]:
torch.einsum('ij,ij->ij', x, x)

tensor([[0.0013, 0.1393, 0.0866],
        [0.8473, 0.0467, 0.9871]])

### Outer product

In [25]:
a = torch.rand((3))
b = torch.rand((5))
print(a)
print(b)

tensor([0.2377, 0.5494, 0.8985])
tensor([0.6647, 0.0199, 0.2664, 0.6864, 0.8842])


In [26]:
torch.einsum('i,j->ij', a, b)

tensor([[0.1580, 0.0047, 0.0633, 0.1632, 0.2102],
        [0.3652, 0.0109, 0.1464, 0.3771, 0.4858],
        [0.5973, 0.0179, 0.2394, 0.6167, 0.7944]])

### Batch matrix multiplication

### Matrix diagonal